### ISSUE TITLE
Example with Y.js ?

### ISSUE THREAD

**Issue by MentalGear** [local-first-web/auth#97]
I came here looking for a solution that allows access control for Y.Docs. You're library is really impressive and thank you for the dedicated work!

I'm not quite sure if Y.js can be used as a storage within crdx. An example with it in the Readme would certainly help making your library more accessible (and afterwards a link back from Y.js github page).

**Comment by HerbCaudill** [comment]
Hi - I'm not very familiar with Y.js or Y.Docs so I wouldn't be the right one to create this example, but I'd be receptive to a PR! 

The `auth-provider-automerge-repo` package shows how this library can be used alongside another crdt (Automerge) so maybe it would be instructive.
